version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: rc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: repair_center
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: rc_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: rc_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src:ro

  frontend:
    build: ./frontend
    container_name: rc_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/app/src:ro

volumes:
  mysql_data:
